import type { Metadata } from "next";
import {
	Geist,
	Geist_Mono,
	Roboto,
	Roboto_Mono,
	Roboto_Serif,
} from "next/font/google";
import "./globals.css";

const roboto = Roboto_Mono({
	weight: ["200", "400", "500", "700"],
	subsets: ["latin"],
});

const robotoSerif = Roboto_Serif({
	variable: "--font-roboto-serif",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${roboto.className} ${robotoSerif.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
